In [1]:
import pandas as pd

In [2]:
# load datasets
df = pd.read_csv('Data/merged_data.csv')

<class 'pandas.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sample  1025 non-null   str
 1   cancer  1025 non-null   str
dtypes: str(2)
memory usage: 16.1 KB

,Ensembl_ID,TCGA-KN-8431-01A,TCGA-KN-8433-11A,TCGA-KN-8433-01A,TCGA-KO-8407-01A,TCGA-KL-8331-01A,TCGA-KL-8336-01A,TCGA-KM-8439-01A,TCGA-KO-8403-01A,TCGA-KL-8332-11A,...,TCGA-5P-A9KE-01A,TCGA-Y8-A894-01A,TCGA-B1-7332-01A,TCGA-A4-A5Y1-01A,TCGA-2Z-A9J6-01A,TCGA-A4-7828-01A,TCGA-5P-A9JY-01A,TCGA-BQ-7060-01A,TCGA-UZ-A9PS-01A,TCGA-UZ-A9PS-05A
0,ENSG00000000003.15,2.922369,5.082860,3.150982,3.515813,4.721969,3.356116,4.203961,3.459891,5.150450,...,4.130774,4.299377,4.664119,4.944034,4.111883,4.197716,3.870740,3.627268,4.520950,3.258052
1,ENSG00000000005.6,0.040121,1.430767,0.000000,0.363227,0.391878,0.110363,0.000000,0.217479,1.311271,...,0.022758,0.181039,0.022758,1.702259,0.925544,0.095857,0.591009,0.045303,0.018207,0.191815
2,ENSG00000000419.13,5.234570,4.708689,4.683680,5.020418,5.243284,4.274329,4.705160,5.167354,5.372987,...,4.656777,4.270163,4.781150,4.840504,4.298460,4.490262,4.735777,3.999838,4.710751,4.636114
3,ENSG00000000457.14,0.836086,1.613485,0.919607,0.969160,1.116431,1.315914,1.369606,1.037593,1.878843,...,1.208205,1.994435,0.909351,1.993493,1.205705,1.195159,1.342896,1.167807,1.027933,1.422664
4,ENSG00000000460.17,0.257011,0.456596,0.326882,0.437121,0.407298,0.614474,0.335026,0.366028,0.415326,...,0.493750,0.538935,0.300417,1.061914,0.413052,0.582171,0.464982,0.415434,0.635615,0.438825

             sample                                  cancer
0  TCGA-UW-A72Q-01A  Renal cell carcinoma, chromophobe type
1  TCGA-KM-8442-01A  Renal cell carcinoma, chromophobe type
2  TCGA-KL-8328-01A  Renal cell carcinoma, chromophobe type
3  TCGA-KN-8430-11A  Renal cell carcinoma, chromophobe type
4  TCGA-KN-8430-01A  Renal cell carcinoma, chromophobe type